# Autogenerated file
def render(networks):
    yield """<!doctype html>
<html>
  <head>
    <title>Microdot + uTemplate example</title>
    <meta charset=\"UTF-8\">
  </head>
  <body>
      <div>
        <h2>Configurar Nombre del Dispositivo</h2>
        <form action=\"/save\" method=\"post\">
            <label for=\"device_name\">Nombre del Dispositivo:</label><br>
            <input type=\"text\" id=\"device_name\" name=\"device_name\"><br><br>
            
            <div>
                <p>Redes WIFI disponibiles:</p>
                
                """
    for ssid in networks:
        yield """                    <input type=\"radio\" id=\"ssid-"""
        yield str(ssid)
        yield """\" name=\"ssid\" value=\""""
        yield str(ssid)
        yield """\">
                    <label for=\"ssid-"""
        yield str(ssid)
        yield """\">"""
        yield str(ssid)
        yield """</label><br>
                """
    yield """                
            </div>
            
            <input type=\"text\" id=\"password\" name=\"password\"><br><br>
            
            <input type=\"submit\" value=\"Guardar\">
        </form>
       </div>
  </body>
</html>"""
